### ISSUE TITLE
use HTML inline

### ISSUE THREAD

**Issue by mreinhart** [MathiasPaumgarten/grunt-bake#40] opened 2015-02-23 19:51 UTC
Is it possible to use html when supplying inline content? For example  I think that it chokes on the span tags unless there is a way to escape them that I'm not aware of.

**Comment by MathiasPaumgarten** [comment] 2015-02-24 22:06
Hey there, thanks for the issue. The problem is the regex used to parse the files and look for bake anchor tags: https://github.com/MathiasPaumgarten/grunt-bake/blob/master/tasks/bake.js#L57

It won't work correctly because it doesn't allow any `>` inside the bake tag. This could and should be updated tho accept any character until it hits a `)-->` closing tag. I think this can be accomplished with look-aheads in Regex. I am not a  master at those. However I will put this on my list to look at. Sorry for the bad news.

**Comment by shammar13** [comment] 2015-05-08 15:03
@MathiasPaumgarten Has there been any progress on this? It would be a really useful feature.

**Comment by MathiasPaumgarten** [comment] 2015-05-11 15:05
Hey there, sorry I haven't worked on grunt-bake in a while. Do you have any experience with RegEx in JS?

**Comment by shammar13** [comment] 2015-05-12 13:55
I only have a small amount of RegEx experience in JS. But I am willing to help out if I can.

Maybe the fix is as simple as removing that constraint on not allowing any `>` inside the bake tag? That way the bake tag can accept anything.

**Comment by mreinhart** [comment] 2015-05-12 13:56
Unfortunately I'm not great with RegEx.

**Comment by MathiasPaumgarten** [comment] 2015-05-12 14:09
What one would need to do is make a regex that accepts everything until it hits a `-->`.
I'm pretty sure that is doable with look-aheads. But I can't do that off the pat.

**Comment by shammar13** [comment] 2015-05-12 15:08
I think I found a fix.

I replaced the RegEx here: https://github.com/MathiasPaumgarten/grunt-bake/blob/master/tasks/bake.js#L57 with this:

```js
var regex = /(\n?)([ |\t]*)<!--\(\s?bake\s+([\w\/.\-]+)\s?([^]*?)\)-->/g;
```

I gave it a quick test, and it's basically allowing me to put HTML inline:
```html
<!--(bake /templates/component/_component_name.html title="<h2>Some Title<h2>")-->
```

Or I can include the HTML markup in the JSON content file:
```js
{
    "index": {
        "title": "<h2>Some Title</h2>"
    }
}
```

@mreinhart + @MathiasPaumgarten do you guys mind giving it a look over to see if it works for you guys too?

I haven't forked this repo or anything, so you just need to change that RegEx on your guys' versions.

**Comment by MathiasPaumgarten** [comment] 2015-05-12 15:29
Hey @shammar13,

just saw your EDIT. I also added it. I'm willing to take your PR though. Your fix works. I'm still working it out that it works for inline bakes as well. such as:

```html
            <!--(bake-start bar="<span>bar</span>")-->
                {{bar}}
            <!--(bake-end)-->
```

**Comment by MathiasPaumgarten** [comment] 2015-05-12 15:41
Again here. I saw that you updated your repo, with the same update. I also added a little test to my repo and make sure it breaks nothing. I updated it on __npm__ to `0.3.13`. This should allow you to work with it in your projects for now. 

I hope that by tonight I have a second push to fix my issue mentioned above as well. 

Thanks for the contribution.

**Comment by shammar13** [comment] 2015-05-13 07:08
@MathiasPaumgarten Thanks for being so quick to help resolve this :+1: 

I'm deleting my fork and using this repo instead.

**Closed** 2015-08-10 20:36 UTC
